### ISSUE TITLE
False error in SAM "Policies"

### ISSUE THREAD

**Issue by jashanbhullar** [ScottBrenner/cfn-lint-action#20]
This template gives an error
```
GenericLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: path/to/code
            Policies:
                - S3ReadPolicy:
                      BucketName: !Ref BucketName
                - S3WritePolicy:
                      BucketName: !Ref SomeOtherBucket
                - AWSSecretsManagerGetSecretValuePolicy:
                      SecretArn: !Ref SomeSecretKey
            MemorySize: 2048
            Timeout: 600
```

Error:
```
Error transforming template: Resource with id [GenericLambdaFunction] is invalid. Policy at index 1 in the 'Policies' property is not valid
```

Couldn't find an resolution to this?
Can we disable it for some lines or something else can solve this?
