### ISSUE TITLE
Action build times are slow

### ISSUE THREAD

**Issue by moltar** [ScottBrenner/cfn-lint-action#28]
It takes 3 to 4 minutes to build the image for actions.

I am talking the actual image build step, not the cfn build steps.

Is there anything that can be done to improve this?

![image](https://user-images.githubusercontent.com/491247/110228704-d0eb2e00-7f35-11eb-8302-73b062ca8d92.png)

**Comment by ScottBrenner** [comment]
Duplicates #23, following which a pre-build image is now available for use - https://github.com/users/ScottBrenner/packages/container/package/cfn-lint-action

**Comment by moltar** [comment]
Amazing. Thank you 🙏

**Comment by moltar** [comment]
Sorry for being dense, but I can't figure out how to use the pre-built package.

I've tried many things, and every attempt is rebuilding it.

Things I've tried:

```yml
      - name: CDK Lint
        uses: scottbrenner/cfn-lint-action@master
        with:
          args: "cdk.yml --ignore-checks W3005"
```

```yml
      - name: CDK Lint
        uses: scottbrenner/cfn-lint-action@d389483b9ad1e435844ec7a5792ac5d5f9c87ba6
        with:
          args: "cdk.yml --ignore-checks W3005"
```

```yml
      - name: CDK Lint
        uses: scottbrenner/cfn-lint-action@master
        with:
          registry: ghcr.io
          args: "cdk.yml --ignore-checks W3005"
```

```yml
      - name: CDK Lint
        uses: scottbrenner/cfn-lint-action@d389483b9ad1e435844ec7a5792ac5d5f9c87ba6
        with:
          registry: ghcr.io
          args: "cdk.yml --ignore-checks W3005"
```

Thanks!
