### ISSUE TITLE
ERROR - Could not write the graph in DOT format.

### ISSUE THREAD

**Issue by hcdiekmann** [ScottBrenner/cfn-lint-action#326]
**Describe the bug**
Using ``-g``  flag to generate DOT model gives missing pydot pygraphviz ERROR, although installed

**To Reproduce**
```yml
name: Lint CloudFormation Templates

on:
  push:
    branches:
      - main

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Install pydot and pygraphviz
        run: |
          sudo apt-get install graphviz graphviz-dev
          pip install pygraphviz
          pip install pydot

      - name: Run Linter and generate DOT files
        run: |
          cfn-lint --version
          cfn-lint -g -t cloudformation/templates/*.yaml

      - name: Commit and push DOT files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cloudformation/templates/*.dot
          git commit -m "Add generated DOT graph" || echo "No changes to commit"
          git push
```

**Expected behavior**
Creates a file in the same directory as the template that models the template's resources in DOT format

**Screenshots**
![image](https://github.com/ScottBrenner/cfn-lint-action/assets/13176191/a564b6f5-0e69-4537-addf-99439e7486fd)

**GitHub Actions Runner configuration (please complete the following information):**
 - OS: ubuntu-latest
