### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by jeandoBet** [ScottBrenner/cfn-lint-action#419]
**Describe the bug**
Latest version is blocked to 0.* , as 1.9.* version is now available.

**To Reproduce**
```
    - name: Setup Cloudformation Linter
      uses: scottbrenner/cfn-lint-action@v2

    - name: Print the Cloud Formation Linter Version & run Linter.
      shell: bash
      run: |
        cfn-lint --version
```
output: 
```
| cfn-lint
| 0.87.10
```

it should install the latest version, as of today: 1.9.5 .

It works when it's specified : 

```
    - name: Setup Cloudformation Linter
      uses: scottbrenner/cfn-lint-action@v2
      with:
        version: 1.*

    - name: Print the Cloud Formation Linter Version.
      shell: bash
      run: |
        cfn-lint --version
```

output: 
```
| cfn-lint
| 1.9.5
```

**Additional context**
Seems to be due to the default value (0.*) set in : https://github.com/ScottBrenner/cfn-lint-action/blob/adb118b1e813ff33c3a632550253889973c65fdb/dist/index.js#L84
