### ISSUE TITLE
Broken v2 when upgrading package

### ISSUE THREAD

**Issue by rbusato-ts** [ScottBrenner/cfn-lint-action#495]
**Describe the bug**
this particular change `https://github.com/ScottBrenner/cfn-lint-action/commit/0696545a68edbeb39abe4090b230845d7b715e8e#r154033366` broke our cfn-lint checks. we were pointing to cfn-lint-action@v2 which looks like it was updated 3 days ago and brought in this change with it causing things to break on our side. workaround was to point to cfn-lint-action@v2.4.7

cc @ScottBrenner 

**To Reproduce**
```
- name: Setup CloudFormation Linter
  uses: scottbrenner/cfn-lint-action@v2
  with:
    version: 1.24.0
```

**Expected behavior**

**Screenshots**

**GitHub Actions Runner configuration (please complete the following information):**
 - OS: ubuntu-22.04
 - Inputs: version=1.24.0
 - Version: v2
